Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 211, in <module>
    vert_EKE  = vertical_integral(EKE )
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 204, in vertical_integral
    M         = weighted(reshape(m))                 # (year, month,days, hour, plev, lat, lon)         
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Calculate_EKE_depths.py", line 193, in reshape
    y1=y[0:30*12*4,...].reshape((no_of_years,no_of_months,days,hours,len(sigma_full),len(lat),len(lon)))
ValueError: cannot reshape array of size 454118400 into shape (1,12,30,4,24,90,144)
Traceback (most recent call last):
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Reload_EKE_save_interpolated_depths.py", line 78, in <module>
    raw_data.append(load(source+"EKE.hkl"))    
  File "/project2/tas1/pragallva/Fall_quarter_2018//codes/python_scripts/am2/Reload_EKE_save_interpolated_depths.py", line 38, in load
    dictionary = hkl.load(filename)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/hickle/hickle.py", line 491, in load
    with file_opener(fileobj) as h5f:
  File "/home/pragallva/Project1/lib/python2.7/site-packages/hickle/hickle.py", line 173, in file_opener
    h5f = h5.File(filename, mode)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/pragallva/Project1/lib/python2.7/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-install-6ALcG4/h5py/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-install-6ALcG4/h5py/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-install-6ALcG4/h5py/h5py/h5f.c:2120)
IOError: Unable to open file (unable to open file: name = '/project2/tas1/pragallva/Fall_quarter_2018/post_process_data/am2/HC59_la50m_oc2m0/EKE.hkl', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
